### ISSUE TITLE
levenshtein searcher works incorrectly

### ISSUE THREAD

**Issue by oserikov** [deeppavlov/DeepPavlov#1462]
**DeepPavlov version** (you can look it up by running `pip show deeppavlov`): 0.15.0

**Python version**: 3.7.10

**Operating system** (ubuntu linux, windows, ...): ubuntu 20.04

**Issue**: Levenshtein searcher does not take symbols replacements into account

**Command that led to error**:
```
>>> from deeppavlov.models.spelling_correction.levenshtein.searcher_component import LevenshteinSearcher
>>> vocab = set("the cat sat on the mat".split())
>>> abet = set(c for w in vocab for c in w)
>>> searcher = LevenshteinSearcher(abet, vocab)
>>> 'cat' in searcher
True
>>> searcher.transducer.distance('rat', 'cat'),\
...  searcher.transducer.distance('cat', 'rat')
(inf, inf)
>>> searcher.transducer.distance('at', 'cat')
1.0
>>> searcher.transducer.distance('rat', 'cat')
inf
>>> searcher.search("rat", 1)
[]
>>> searcher.search("at", 1)
[('mat', 1.0), ('cat', 1.0), ('sat', 1.0)]
```

**Expected output**:
```
>>> searcher.transducer.distance('rat', 'cat')
1.0
>>> searcher.search("rat", 1)
[('mat', 1.0), ('cat', 1.0), ('sat', 1.0)]
```

**Comment by Kolpnick** [comment]
Hi, @oserikov!
Due to the peculiarity of our implementation of the Levenshtein distance calculation, it is required to add all possible alphabet characters to the vocabulary. So, if you want `searcher.transducer.distance('cat', 'rat')` to work correctly, it is necessary to add the letter `r` to the vocabulary: `vocab = set("the cat sat on the red mat".split())`. For more details, see the screenshot.
If you are still having questions about this, please let us know.
![image](https://github.com/deeppavlov/DeepPavlov/assets/99244955/480db18c-3e50-4462-9447-f5989d6ee397)
